---
- name: Determine if Atomic
  command: "test -f /run/ostree-booted"
  register: is_atomic
  ignore_errors: yes
  changed_when: false

- name: Determine if firewalld installed
  command: "rpm -q firewalld"
  register: has_firewalld
  ignore_errors: yes
  changed_when: false

- name: Determine if iptables-services installed
  command: "rpm -q iptables-services"
  register: has_iptables
  ignore_errors: yes
  changed_when: false

- name: Update to latest OS

- name: Update to lastest Atomic tree

- name: Install the required master software

- name: Set up repo files

